on:
  push:
    branches: [ main ]
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    name: Build .ipk packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23b

      - name: Build .ipk
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: ./build_ipk.sh

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dji-moonlight-shim-${{ github.sha }}.ipk
          path: ./ipk/build/dji-moonlight-shim.ipk

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download release artifacts
        uses: actions/download-artifact@v2
        with:
          name: dji-moonlight-shim-${{ github.sha }}.ipk

      - name: Read metadata
        run: |
          VERSION=$(dpkg-deb -f ipk/build/dji-moonlight-shim.ipk Version)
          ARCH=$(dpkg-deb -f ipk/build/dji-moonlight-shim.ipk Architecture)
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=arch::$ARCH"

      - name: Rename release artifacts
        run: |
          PKG_NAME=dji-moonlight-shim_${{ steps.read-metadata.outputs.version }}_${{ steps.read-metadata.outputs.arch }}.ipk
          mv dji-moonlight-shim-${{ github.sha }}.ipk $PKG_NAME
          echo "::set-output name=package::$PKG_NAME"

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ steps.rename.outputs.package }}

