on:
  push:
    branches: [ main ]
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    name: Build .ipk packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23b

      - name: Build .ipk
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: ./build_ipk.sh

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dji-moonlight-shim-${{ github.sha }}.ipk
          path: ./ipk/build/dji-moonlight-shim.ipk
